# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Naveen
tagline:          'Σ ∞'
description:      ''
url:              http://nvenkataraman1.github.io
baseurl:          /

author:
  name:           'Naveen Venkataraman'
  url:            https://twitter.com/nvenkataraman1

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nvenkataraman1

